Recupero url su community channel + varie
Stream4me/addon pull request #329
Opened 2021-07-24 23:48 UTC by 4l3x87

Ho aggiunto la possibilità di recupero deigli url nel community channel (solamente gli url validi con  mimetype).
In più ho messo la possibilità di disattivare per ogni singolo item la videoteca ed attivare l'autoplay (che bypassa per questo canale la configurazione generica).
Queste modifiche le ho realizzate per fruite di questo canale:
http://kod-community-channels.herokuapp.com/torino-channel

2021-08-17 16:35 UTC, mac12m99 commented
Ciao,
ho finalmente avuto un attimo per guardare questa pull: per me va bene, l'unica cosa su cui non concordo è la funzione is_valid_url.
Immagino tu l'abbia inserita in quanto chiamando servertools.find_video_items ti trova dei falsi server "diretti", e qui direi che piuttosto che filtrarli dopo è meglio risolvere il problema alla radice, ovvero in servers/directo.json, aggiustando le regex.
Quelle regex provengono da alfa ed è probabile non vengano utilizzate, quindi potrebbero bastare un paio di regex per rilevare m3u8 e mp4 (in maniera più precisa, ad esempio escludendo gli spazi)

2021-08-17 18:40 UTC, 4l3x87 commented
Ok appena ho un attimo faccio questa variazione!

2021-08-18 15:24 UTC, 4l3x87 commented
Ciao @mac12m99 , ho modificato il pattern del server, però è nata l'esigenza (sul mio canale) di filtrare solamente alcuni tipi di video gli m3u8, per cui ho previsto la possibilità sul canale community di passare dei pattern per filtrare i risultati trovati. Fammi sapere cosa ne pensi.

2021-08-19 09:49 UTC, mac12m99 requested changes
Per me va bene, ho inserito solo qualche consiglio per migliorare la leggibilità.
Queste aggiunte comunque andrebbero documentate, al momento l'unica "documentazione" che abbiamo è questa: https://telegra.ph/Guida-Community-Channel-KoD-07-06, se riesci a scrivere 2 righe sui cambiamenti li includo nella guida.

2021-08-19 09:49 UTC, mac12m99 commented on servers/directo.json
> +        "pattern": "((?:http://|https://).\\S+.(m3u8|mp4|mpeg|mpd|flv)[^\"'\n]*)",
Va bene, anche se per comodità potevi usare
https?://

2021-08-19 09:49 UTC, mac12m99 commented on specials/community.py
> +                    if 'patterns' in item.url and item.url['patterns']:
item.url.get('patterns') fa la stessa cosa ed è più leggibile

2021-08-19 09:49 UTC, mac12m99 commented on specials/community.py
> +                            match = re.search(re.compile(pattern), item_url.url)
re.compile è inutile, puoi ometterlo

2021-08-20 00:00 UTC, 4l3x87 commented
Ciao mac12m99, ho applicato alcuni fix tra cui quelli che mi hai consigliato, ho dovuto aggiungere il controllo se l'url è di un server conosciuto altrimenti non funzionava se venivano inseriti url di server conosciuti.
Per quanto riguarda la documentazione, provo a scriverti un paio di righe appena riesco.

2021-08-20 12:22 UTC, mac12m99 commented
Ciao,
purtroppo ho trovato un problema: talvolta potrebbero esserci dei link diretti al video che non possiedono alcuna estensione, in questi casi, non riconoscendo l'estensione dall'url ne essendo un server conosciuto, cade nel caso che hai aggiunto te (ricerca di server all'interno dell'html della pagina). Ma siccome si tratta di un link diretto inizia a scaricare il file, bloccando kodi fino alla fine del download..
Puoi trovare degli esempi all'interno di tiny.cc/ingordi, sezione film
https://github.com/MikeKOD/ingordichannel/blob/update/FILM/film.json

A questo punto direi che è più semplice creare 2 chiavi: links (che agisce come ha sempre fatto) e un'altra che contiene la pagina in cui cercare i server, esempio (sentiti libero di cambiare la struttura):
{
   "data": {
         "url": "https://tv.torinofc.it/diretta-live",
         "patterns": [
                "^(?:https?://).\\S+.m3u8$"
            ]
    }
}
Mi rendo conto si tratta di una modifica "radicale" ma credo sia il modo migliore

2021-08-24 13:28 UTC, 4l3x87 commented
Ciao @mac12m99, ho fatto alcune modifiche, la chiave l'ho chiamata "find_links", ho aggiunto il supporto con gli short link, fammi sapere che ne pensi. Per quanto riguarda la documentazione non sono ancora riuscito a scriverti 2 righe (sono nell'unico camping senza rete internet) appena riesco ti invio cosa aggiungere nella guida

2021-08-26 16:19 UTC, merged

2021-08-26 16:24 UTC, mac12m99 commented
Mi sembra ok, grazie del contributo!
Aspetto la documentazione, nel frattempo ti auguro buone vacanze :)